apiVersion: batch/v1
kind: CronJob
metadata:
  name: scale-up
spec:
  schedule: "59 7 * * 1-5"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: deployment-scaler-account
          automountServiceAccountToken: true
          containers:
            - name: scale-up
              image: bitnami/kubectl
              args: ["scale", "deploy", "-l", "isScheduled=true", "--replicas=1"]
          restartPolicy: Never
